# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY /opt/checkout/react-todo-app/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY /opt/checkout/react-todo-app .

# Build the React app
RUN npm run build

# Install serve to serve the build folder
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 3000

# Serve the build folder on port 3000
CMD ["serve", "-s", "build"]
